---
name: drone
kind: pipeline
type: docker

volumes:
  - name: targetJar
    host:
      path: /home/repository  # the machine directory

service:
  - name: database
    image: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

steps:
#  - name: publish
#    image: plugins/docker
##    volumes:
##      - name: targetJar
##        path: /var/lib # the container directory
#    settings:
#      repo: zoe27/demo
#      tags: latest
#      dockerfile: dockerfilev1
#      username:
#        from_secret: push_user
#      password:
#        from_secret: push_pass
#
#
#
#  - name: deploy
#    image: appleboy/drone-ssh
#    settings:
#      host:
#        from_secret: host
#      username:
#        from_secret: user
#      password:
#        from_secret: pass
#      port: 22
##      command_timeout: "300" # ssh命令行执行超时时间，300秒
#      script:
#        - cd /home/repository
#        - docker pull zoe27/demo:latest
#        - docker rm -f salary-service || true # 这里这样是因为如果不存在docker-demo，rm会报错
#        - docker run -d -p 80:8089 --network bridge --link my_mysql:db --name salary-service zoe27/demo

  - name: test
    image: mysql
    commands:
      - sleep 15
      - mysql -u root -h database --execute="SELECT VERSION();"



trigger:
  branch:
    - master
  event:
    - push

