---
name: drone
kind: pipeline
type: docker

volumes:
  - name: targetJar
    host:
      path: /home/repository  # the machine directory

steps:
  - name: build
    image: redis:6.2.1
    commands:
    - echo "hello world"
    - echo "this is the first time to test drone"

#  - name: test
#    image: maven:3-jdk-8
#    volumes:
#      - name: targetJar
#        path: /drone/src/target # the container directory
#    commands:
#      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
##      - rm -rf `ls /drone/src/target/ | grep -v jar`
#      - pwd
#      - ls
#      - cd target
##      - cp *.jar
#      - rm -rf !\(*.jar\)

#  - name: deploy
#    image: plugins/docker
#    volumes:
#      - name: targetJar
#        path: /var/lib
#    settings:
#      dockerfile: dockerfilev1
#      tags: latest

  - name: publish
    image: plugins/ecr:latest
    repo: zoe27/demo
    dockerfile: dockerfilev2




trigger:
  branch:
    - master
  event:
    - push

