---
name: drone
kind: pipeline
type: docker

volumes:
  - name: targetJar
    host:
      path: /home/repository

steps:
  - name: build
    image: redis:6.2.1
    commands:
    - echo "hello world"
    - echo "this is the first time to test drone"

  - name: test
    image: maven:3-jdk-8
    volumes:
      - name: targetJar
        path: /drone/src/target
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - pwd
      - ls
      - ls target
      - ls targetJar
      - cp -rf target/* targetJar

  - name: deploy
    image: redis:6.2.1
    commands:
      - echo "start to deploy service"

trigger:
  branch:
    - master
  event:
    - push

