---
name: drone
kind: pipeline
type: docker

volumes:
  - name: targetJar
    host:
      path: /home/repository  # the machine directory
  - name: mydir
    host:
      path: /home/server/mydir
  - name: my.cnf
    host:
      path: /home/server/conf/my.cnf
  - name: datadir
    host:
      path: /home/server/datadir
  - name: dockerDir
    host:
      path: /root/docker

service:
  - name: database
    image: mysql
    container_name: my_mysql_1
    volumes:
      - ./mydir:/mydir
      - ./datadir:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ~/root/docker:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3308:3306

steps:
  - name: publish
    image: plugins/docker
#    volumes:
#      - name: targetJar
#        path: /var/lib # the container directory
    settings:
      repo: zoe27/demo
      tags: latest
      dockerfile: dockerfilev1
      username:
        from_secret: push_user
      password:
        from_secret: push_pass

  - name: mysql
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pass
      port: 22
      #      command_timeout: "300" # ssh命令行执行超时时间，300秒
      script:
        - cd /home/server
        - pwd
        - docker rm -f mysql_1
        - docker run -d -p 4306:3306
          --restart always
          --privileged=true
          --name mysql_1
          -e MYSQL_USER="root"
          -e MYSQL_PASSWORD="123456"
          -e MYSQL_ROOT_PASSWORD="123456"
          -v /home/server/mydir:/mydir
          -v /home/server/datadir:/var/lib/mysql
          -v /home/server/conf/my.cnf:/etc/mysql/my.cnf
          -v /root/docker:/docker-entrypoint-initdb.d
          mysql:5.7.16

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pass
      port: 22
#      command_timeout: "300" # ssh命令行执行超时时间，300秒
      script:
        - cd /home/repository
        - docker pull zoe27/demo:latest
        - docker rm -f salary-service || true # 这里这样是因为如果不存在docker-demo，rm会报错
        - docker run -d -p 80:8089 --link mysql_1:db --name salary-service zoe27/demo


trigger:
  branch:
    - master
  event:
    - push

