version: '2'

services:
  drone-server:
    image: drone/drone:1.6                  #

    ports:
      - outerport:serviceport                             #
    volumes:
      - /var/lib/drone:/data
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com                    #b
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}          #
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}  #
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}                      #
      - DRONE_SERVER_HOST=204.44.87.9                    #
      - DRONE_SERVER_PROTO=http                  #
      - DRONE_LOGS_TRACE=true
      - DRONE_USER_CREATE=username:{USER_NAME},admin:true # set USER_NAME as administrator, we can set truested then


  drone-agent:
    image: drone/agent:1.6

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=ip:port
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}        #
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
      - DRONE_LOGS_TRACE=true
